### ISSUE TITLE
Clarification on maven

### ISSUE THREAD

**Issue by cbetta** [interfax/interfax-java#11]
@anuragkapur does this work as is? Or does `${latest-version}` need to be replaced by `0.1.0`?

``` xml
<dependency>
  <groupId>net.interfax</groupId>
  <artifactId>api-client</artifactId>
  <version>${latest-version}</version>
</dependency>
```

**Comment by anuragkapur** [comment]
It actually needs to be replaced with an available version number. My assumption was that most java developers would get it, but I should probably not make any assumptions. I have also added the maven version number badge alongside the travisCI badge.

Will update to the following:

``` xml
<dependency>
  <groupId>net.interfax</groupId>
  <artifactId>api-client</artifactId>
  <version>${version-number}</version>
</dependency>
```

Where ${version-number} should be replaced with a real version number from the versions available in [maven central](http://search.maven.org/#search%7Cga%7C1%7Cnet.interfax.api-client).

Ok?

**Comment by cbetta** [comment]
@anuragkapur agreed that most will get it, just trying to cover the "some" who won't ;)

Can you add the note: "Replace `${version-number}` with your preferred version number" under the code sample?

**Comment by anuragkapur** [comment]
Done: https://github.com/interfax/interfax-java#include-as-maven-dependency

**Comment by cbetta** [comment]
@anuragkapur closing, but please make sure to also add the right syntax highlighting and some code brackets around the `%{version-number}` bit. (As I did here)

**Comment by anuragkapur** [comment]
Done. https://github.com/interfax/interfax-java/commit/12ad1e70b13edd4d066468f9e5414797b40b02d1
