### ISSUE TITLE
No way to send an in-memory document

### ISSUE THREAD

**Issue by evanjpw** [interfax/interfax-java#16]
With the old API it was possible to send documents using the ``Sendfax_Ex_2`` call without ever writing them to disk. For security, performance and compliance (HIPAA) reasons that is *very* helpful.

I would like to ask that sendFax methods be added that take one or more input streams (or even byte arrays) and corresponding mime hints so that this function can be reproduced. With input streams, ``StreamDataBodyPart`` exists as a natural analog to ``FileDataBodyPart``, so the code in the File array version of ``sendFax`` could be easily modified.

Having to write and manage temporary files that contain secure data is problematic.

**Comment by anuragkapur** [comment]
Thanks for raising this and also submitting a PR to address the issue. I have merged your PR https://github.com/interfax/interfax-java/pull/17. Additionally, made a minor update to your PR via https://github.com/interfax/interfax-java/pull/18 and merged that too.

Version `0.6` (https://oss.sonatype.org/content/repositories/releases/net/interfax/api-client/0.6/) of the library now contains both the updates mentioned above.

**Comment by evanjpw** [comment]
Thank you. I appreciate how quickly you took my PR. And I am encouraged to
help out further. Thank you very much.

**Comment by cbetta** [comment]
@anuragkapur just looking at this code now, just checking why it still needs the filename? From what I can tell it just needs it to determine the mime type. Can we instead just pass in the mime type explicitly? We have done the same in Ruby, Node and Python.

**Comment by anuragkapur** [comment]
@cbetta - you are correct, it is only being used to detect mime type, which can be passed explicitly instead of filenames. I'll make the change as a new PR shortly.
