### ISSUE TITLE
Some methods expect Strings where the API returns Longs

### ISSUE THREAD

**Issue by cbetta** [interfax/interfax-java#22]
I ran into this issue here:

```java
// get the faxes
InboundFaxStructure[] faxes = interfax.getInboundFaxList(
  Optional.of(options)
);

for (InboundFaxStructure fax : faxes) {
  byte[] image = interfax.getInboundFaxImage(fax.getMessageId());
}
```

This doesn't work as `getMessageId()` returns a long and `getInboundFaxImage()` requires a string.

**Comment by anuragkapur** [comment]
Good spot, i'll make the types used across consistent.

**Comment by anuragkapur** [comment]
Addressed in https://github.com/interfax/interfax-java/pull/30
