### ISSUE TITLE
Automated release process

### ISSUE THREAD

**Issue by anuragkapur** [interfax/interfax-java#4]
- auto-tag
- use github releases section
- push to maven central

**Comment by anuragkapur** [comment]
Done, all commits to master are compiled, tested and if successful, pushed to maven central and auto-tagged.

**Comment by cbetta** [comment]
@anuragkapur can you make sure to document this somewhere? I'm mainly thinking about: what is the correct process for us, you, or any other Java dev to make any changes to this library and get them released to a new version? How are new version numbers determined? Is this a manual choice or automatically incremented?

**Comment by anuragkapur** [comment]
@cbetta - does this do the job: https://github.com/interfax/interfax-java/blob/versioning/README.md#releasing ?

Note: I have consciously left out patch version. Patch releases can be done, but require careful manual tweaking of version numbers. It would be much easier to do a minor release instead, IMO. Ok or are patch releases necessary?

**Comment by cbetta** [comment]
@anuragkapur looks good. Just one typo: semver, not semvar.
