### ISSUE TITLE
Add syntax highlighting to README

### ISSUE THREAD

**Issue by cbetta** [interfax/interfax-java#5]
@anuragkapur can we please add some syntax highlighting to the code samples?

You currently used indentation to make code samples:

```
    InterFAXClient interFAXClient = new InterFAXJerseyClient();
    APIResponse apiResponse = interFAXClient.hideFax("667915469");
```

If you replace this with backticks you can specify a language as well and get syntax highlighted code.

``````
```java
InterFAXClient interFAXClient = new InterFAXJerseyClient();
APIResponse apiResponse = interFAXClient.hideFax("667915469");
```
``````

Like this:

``` java
InterFAXClient interFAXClient = new InterFAXJerseyClient();
APIResponse apiResponse = interFAXClient.hideFax("667915469");
```

**Comment by anuragkapur** [comment]
@cbetta - done: https://github.com/interfax/interfax-java/blob/master/README.md

**Comment by cbetta** [comment]
Excellent. :+1:
