### ISSUE TITLE
Write a simple getting started sample

### ISSUE THREAD

**Issue by cbetta** [interfax/interfax-java#7]
@anuragkapur please have a look at the Getting Started in the ruby library https://github.com/interfax/interfax-ruby

As you can see it's not the point to explain how to initialise the client, instead it's a few lines to demonstrate how to use the library to send a fax, and check it's status. Please move the client section to under Usage and expand the Getting started in the same way as we did for the Ruby library.

**Comment by anuragkapur** [comment]
@cbetta - done: https://github.com/interfax/interfax-java#getting-started
