### ISSUE TITLE
Merge api-credential-configuration.md into README.md

### ISSUE THREAD

**Issue by cbetta** [interfax/interfax-java#8]
@anuragkapur please can we merge the `api-credential-configuration.md` file into the main README?

Additionally:
1. Please use headers instead of bullet points
2. The link to the interfax-api-credentials.yaml is broken

**Comment by anuragkapur** [comment]
@cbetta - sure can do. Reason I kept it separate was to ensure the main README does not get too big and scare people away. Happy to use headers instead of bullets and fix broken link.

You sure you would like me to merge to main README?

**Comment by cbetta** [comment]
Yeah please merge, we did the same in the other projects

**Comment by anuragkapur** [comment]
@cbetta : done: https://github.com/interfax/interfax-java#client
